name: Setup
on:
    workflow_call:
        secrets:
            githubAccessToken:
                required: true

env:
    uniqueWorkspaceId: ${{ vars.ZOS_SANDBOX_DIR }}/setup/${{ github.repository }}/${{ github.ref_name }}/setup_s${{ github.run_number }}
    branch: ${{ github.ref_name }}
    application: ${{ github.event.repository.name }}
    zosHost: ${{ vars.ZOS_HOST }}

jobs:
    Setup:
        runs-on: self-hosted
        steps:
          - name: CI-CD pipeline parameter printout
            run: |
                echo " "
                echo "Following are the CI-CD pipeline parameters"
                echo "*******************************************"
                echo "uniqueWorkspaceId                  = ${{ env.uniqueWorkspaceId}}"
                echo "branch                             = ${{ env.branch}}"
                echo "application                        = ${{ env.application}}"
                echo "zosHost                            = ${{ env.zosHost}}"

          - name: Clone Repo to z/OS Unix System Services
            run: ssh ${{ env.zosHost }} ". ./.profile && gitClone.sh -w ${{ env.uniqueWorkspaceId }} -r https://${{ secrets.githubAccessToken }}@github.com/${{ github.repository }}.git -b ${{ env.branch }}"

    Install:
        needs: Setup
        runs-on: self-hosted
        steps:
          - name: Run Bank of Z installation procedure
            run: ssh ${{ env.zosHost }} ". ./.profile && bash ${{ env.uniqueWorkspaceId }}/${{ env.application }}/.setup/pipeline-remote.sh"

    Cleanup:
        needs:
            - Install
        runs-on: self-hosted
        if: always()
        steps:
          - name: Cleanup Setup Environment
            run: ssh ${{ env.zosHost }} ". ./.profile && deleteWorkspace.sh -w ${{ env.uniqueWorkspaceId }}"
